package com.riskguard.riskcase.service;

import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.riskguard.common.api.ErrorCode;
import com.riskguard.common.api.PageResponse;
import com.riskguard.common.enums.AuditResult;
import com.riskguard.common.enums.CaseStatus;
import com.riskguard.common.enums.RiskDecision;
import com.riskguard.common.exception.BusinessException;
import com.riskguard.common.security.SecurityUtils;
import com.riskguard.common.utils.ClockUtils;
import com.riskguard.common.utils.NoGenerator;
import com.riskguard.decision.dto.RiskDecisionRequest;
import com.riskguard.decision.dto.RiskDecisionResponse;
import com.riskguard.mq.event.RiskCaseCreatedEvent;
import com.riskguard.mq.publisher.RiskEventPublisher;
import com.riskguard.riskcase.dto.CaseActionRequest;
import com.riskguard.riskcase.dto.CaseOperationResponse;
import com.riskguard.riskcase.dto.RiskCaseResponse;
import com.riskguard.riskcase.entity.RiskCase;
import com.riskguard.riskcase.entity.RiskCaseOperationLog;
import com.riskguard.riskcase.mapper.RiskCaseMapper;
import com.riskguard.riskcase.mapper.RiskCaseOperationLogMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.util.List;
import java.util.Optional;

@Service
public class RiskCaseService {

    private final RiskCaseMapper riskCaseMapper;
    private final RiskCaseOperationLogMapper operationLogMapper;
    private final RiskEventPublisher riskEventPublisher;

    public RiskCaseService(RiskCaseMapper riskCaseMapper,
                           RiskCaseOperationLogMapper operationLogMapper,
                           RiskEventPublisher riskEventPublisher) {
        this.riskCaseMapper = riskCaseMapper;
        this.operationLogMapper = operationLogMapper;
        this.riskEventPublisher = riskEventPublisher;
    }

    @Transactional
    public Optional<String> createCaseIfReview(RiskDecisionRequest request, RiskDecisionResponse response) {
        if (!RiskDecision.REVIEW.name().equals(response.decision())) {
            return Optional.empty();
        }
        RiskCase existing = findByDecisionNo(response.decisionNo()).orElse(null);
        if (existing != null) {
            return Optional.of(existing.getCaseNo());
        }

        RiskCase riskCase = new RiskCase();
        riskCase.setCaseNo(NoGenerator.caseNo());
        riskCase.setDecisionNo(response.decisionNo());
        riskCase.setEventNo(response.eventNo());
        riskCase.setUserId(request.userId());
        riskCase.setRiskScore(response.riskScore());
        riskCase.setRiskLevel(response.riskLevel());
        riskCase.setStatus(CaseStatus.PENDING.name());
        riskCaseMapper.insert(riskCase);
        insertOperation(riskCase.getCaseNo(), null, "CREATE", null, CaseStatus.PENDING.name(), "Generated by REVIEW decision");
        riskEventPublisher.publishCaseCreated(new RiskCaseCreatedEvent(
                riskCase.getCaseNo(),
                riskCase.getDecisionNo(),
                riskCase.getEventNo(),
                riskCase.getUserId(),
                riskCase.getRiskScore(),
                riskCase.getRiskLevel(),
                riskCase.getStatus(),
                ClockUtils.now()
        ));
        return Optional.of(riskCase.getCaseNo());
    }

    public Optional<String> findCaseNoByDecisionNo(String decisionNo) {
        return findByDecisionNo(decisionNo).map(RiskCase::getCaseNo);
    }

    public RiskCaseResponse getCase(String caseNo) {
        return RiskCaseResponse.from(requireCase(caseNo));
    }

    public PageResponse<RiskCaseResponse> pageCases(long pageNo, long pageSize, String status, String userId) {
        var query = Wrappers.<RiskCase>lambdaQuery()
                .eq(StringUtils.hasText(status), RiskCase::getStatus, status)
                .eq(StringUtils.hasText(userId), RiskCase::getUserId, userId)
                .orderByDesc(RiskCase::getCreatedAt)
                .orderByDesc(RiskCase::getId);
        Page<RiskCase> page = riskCaseMapper.selectPage(Page.of(pageNo, pageSize), query);
        return PageResponse.of(page.getRecords().stream().map(RiskCaseResponse::from).toList(),
                page.getTotal(), page.getCurrent(), page.getSize());
    }

    @Transactional
    public RiskCaseResponse claim(String caseNo, CaseActionRequest request) {
        RiskCase riskCase = requireCase(caseNo);
        requireStatus(riskCase, CaseStatus.PENDING);
        String before = riskCase.getStatus();
        riskCase.setStatus(CaseStatus.PROCESSING.name());
        riskCase.setAssigneeId(assigneeId(request));
        riskCaseMapper.updateById(riskCase);
        insertOperation(caseNo, operatorId(request), "CLAIM", before, riskCase.getStatus(), remark(request));
        return RiskCaseResponse.from(requireCase(caseNo));
    }

    @Transactional
    public RiskCaseResponse approve(String caseNo, CaseActionRequest request) {
        return finish(caseNo, request, CaseStatus.APPROVED, AuditResult.APPROVE, "APPROVE");
    }

    @Transactional
    public RiskCaseResponse reject(String caseNo, CaseActionRequest request) {
        return finish(caseNo, request, CaseStatus.REJECTED, AuditResult.REJECT, "REJECT");
    }

    @Transactional
    public RiskCaseResponse markFalsePositive(String caseNo, CaseActionRequest request) {
        return finish(caseNo, request, CaseStatus.CLOSED, AuditResult.FALSE_POSITIVE, "MARK_FALSE_POSITIVE");
    }

    @Transactional
    public RiskCaseResponse close(String caseNo, CaseActionRequest request) {
        RiskCase riskCase = requireCase(caseNo);
        String before = riskCase.getStatus();
        riskCase.setStatus(CaseStatus.CLOSED.name());
        riskCaseMapper.updateById(riskCase);
        insertOperation(caseNo, operatorId(request), "CLOSE", before, riskCase.getStatus(), remark(request));
        return RiskCaseResponse.from(requireCase(caseNo));
    }

    public List<CaseOperationResponse> listOperations(String caseNo) {
        requireCase(caseNo);
        return operationLogMapper.selectList(Wrappers.<RiskCaseOperationLog>lambdaQuery()
                        .eq(RiskCaseOperationLog::getCaseNo, caseNo)
                        .orderByAsc(RiskCaseOperationLog::getCreatedAt)
                        .orderByAsc(RiskCaseOperationLog::getId))
                .stream()
                .map(CaseOperationResponse::from)
                .toList();
    }

    private RiskCaseResponse finish(String caseNo, CaseActionRequest request, CaseStatus afterStatus,
                                    AuditResult auditResult, String operation) {
        RiskCase riskCase = requireCase(caseNo);
        if (!CaseStatus.PROCESSING.name().equals(riskCase.getStatus())
                && !CaseStatus.PENDING.name().equals(riskCase.getStatus())) {
            throw new BusinessException(ErrorCode.VALIDATION_FAILED, "Case status cannot be finished: " + riskCase.getStatus());
        }
        String before = riskCase.getStatus();
        riskCase.setStatus(afterStatus.name());
        riskCase.setAuditResult(auditResult.name());
        riskCase.setAuditOpinion(request == null ? null : request.auditOpinion());
        riskCaseMapper.updateById(riskCase);
        insertOperation(caseNo, operatorId(request), operation, before, riskCase.getStatus(), remark(request));
        return RiskCaseResponse.from(requireCase(caseNo));
    }

    private Optional<RiskCase> findByDecisionNo(String decisionNo) {
        return Optional.ofNullable(riskCaseMapper.selectOne(Wrappers.<RiskCase>lambdaQuery()
                .eq(RiskCase::getDecisionNo, decisionNo)));
    }

    private RiskCase requireCase(String caseNo) {
        RiskCase riskCase = riskCaseMapper.selectOne(Wrappers.<RiskCase>lambdaQuery()
                .eq(RiskCase::getCaseNo, caseNo));
        if (riskCase == null) {
            throw new BusinessException(ErrorCode.NOT_FOUND, "Risk case not found: " + caseNo);
        }
        return riskCase;
    }

    private void requireStatus(RiskCase riskCase, CaseStatus expected) {
        if (!expected.name().equals(riskCase.getStatus())) {
            throw new BusinessException(ErrorCode.VALIDATION_FAILED,
                    "Case status must be " + expected.name() + ", current=" + riskCase.getStatus());
        }
    }

    private void insertOperation(String caseNo, Long operatorId, String operation,
                                 String beforeStatus, String afterStatus, String remark) {
        RiskCaseOperationLog log = new RiskCaseOperationLog();
        log.setCaseNo(caseNo);
        log.setOperatorId(operatorId);
        log.setOperation(operation);
        log.setBeforeStatus(beforeStatus);
        log.setAfterStatus(afterStatus);
        log.setRemark(remark);
        operationLogMapper.insert(log);
    }

    private Long operatorId(CaseActionRequest request) {
        return SecurityUtils.currentUserId()
                .orElse(request == null ? null : request.operatorId());
    }

    private Long assigneeId(CaseActionRequest request) {
        if (request != null && request.assigneeId() != null) {
            return request.assigneeId();
        }
        return SecurityUtils.currentUserId().orElse(null);
    }

    private String remark(CaseActionRequest request) {
        if (request == null) {
            return null;
        }
        return StringUtils.hasText(request.remark()) ? request.remark() : request.auditOpinion();
    }
}
